
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
images:
- name: cr7258/http-server
  newName: cr7258/http-server
  newTag: aed55b4e5b1b9eb1eb65063ef02064335b1e6490
