
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
- count: 5
  name: http-server
resources:
- ../../base
- configmap.yaml
images:
- name: cr7258/http-server
  newName: cr7258/http-server
  newTag: 630c991f763c10213ada7b1905fc6328d2289316
