
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
- count: 5
  name: http-server
resources:
- ../../base
- configmap.yaml
images:
- name: cr7258/devops-demo-app
  newName: cr7258/devops-demo-app
  newTag: 5521c76bb1578a937f635f3fe17ba70d2d13b4f7
